# Generated by Django 5.0.7 on 2024-07-13 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0017_alter_horaire_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='moniteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CentreSportif.moniteur'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='prix',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
