# Generated by Django 5.0.7 on 2024-07-14 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CentreSportif', '0018_activite_moniteur_alter_activite_prix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moniteur',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moniteur', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
