# Generated by Django 4.2.14 on 2024-07-13 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CentreSportif', '0018_moniteur_password_moniteur_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moniteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
